icons = {
    "JK/Misc": "🐉 JK/📦 Misc",
    "JK/Reroute": "🐉 JK/🪂 Reroute",
    "JK/ControlNet": "🐉 JK/🕹️ ControlNet",
    "JK/LoRA": "🐉 JK/💊 LoRA",
    "JK/Embedding": "🐉 JK/🌓 Embedding",
    "JK/Loader": "🐉 JK/🐟 Loader",
    "JK/Pipe": "🐉 JK/🎷 Pipe",
    "JK/Image": "🐉 JK/🛩️ Image",
    "JK/Mask": "🐉 JK/🐓 Mask",
    "JK/Latent": "🐉 JK/🦥 Latent",
    "JK/Animation": "🐉 JK/⏲️ Animation",
    "JK/Switch": "🐉 JK/🔀 Switch",
    "JK/Math": "🐉 JK/✖️ Math",
    "JK/Math/Conversion": "🐉 JK/✖️ Math/💠 Conversion",
    "JK/Math/Bool": "🐉 JK/✖️ Math/🥢 Bool",
    "JK/Math/String": "🐉 JK/✖️ Math/🐤 String",
    "JK/Math/Float": "🐉 JK/✖️ Math/🍥 Float",
    "JK/Math/Int": "🐉 JK/✖️ Math/🎡 Int",
    "JK/Math/Number": "🐉 JK/✖️ Math/🔢 Number",
    "JK/Math/Vector": "🐉 JK/✖️ Math/💦 Vector",
    "JK/3D": "🐉 JK/🕒 3D",
    "JK/Audio": "🐉 JK/🎻 Audio",
    "JK/Video": "🐉 JK/🦉 Video",
    "JK/Prompt": "🐉 JK/🐝 Prompt",
    "JK/Experiment": "🐉 JK/⏳ Experiment",
    "JK/Group/Workflow": "🐉 JK/🐙 Workflow",
    "JK/Group/Tools": "🐉 JK/🐒 Tools",
}
